name: 'Setup Oracle Tools'
description: 'Setup Oracle SQL*Plus and Instant Client tools'

runs:
  using: "composite"
  steps:
    - name: Setup Oracle Dependencies (Linux)
      if: ${{ runner.os == 'Linux' }}
      id: setup-oracle-tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip

        cd /tmp
        wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip
        wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-sqlplus-linuxx64.zip

        sudo mkdir -p /opt/oracle
        # Unzip in non-interactive mode
        sudo unzip -o /tmp/instantclient-basiclite-linuxx64.zip -d /opt/oracle 
        sudo unzip -o /tmp/instantclient-sqlplus-linuxx64.zip -d /opt/oracle 

        # Check downloaded version
        INSTANTCLIENT_DIR=$(ls -d /opt/oracle/instantclient_*)
        if [ -z "$INSTANTCLIENT_DIR" ]; then
            echo "Error: Instant Client directory not found!"
            exit 1
        fi

        echo "Oracle Instant Client installed in: $INSTANTCLIENT_DIR"

        # Set environment variables for current step
        export LD_LIBRARY_PATH=$INSTANTCLIENT_DIR:$LD_LIBRARY_PATH
        export PATH=$INSTANTCLIENT_DIR:$PATH

        # Persist environment variables for all subsequent steps
        echo "LD_LIBRARY_PATH=$INSTANTCLIENT_DIR:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
        echo "PATH=$INSTANTCLIENT_DIR:$PATH" >> "$GITHUB_ENV"

        rm -rf /tmp/instantclient*.zip

        sudo apt-get install -y libaio1t64

        sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
        
        # Verify installation
        sqlplus -v
        if [ $? -ne 0 ]; then
            echo "Error: sqlplus command failed to execute!"
            exit 1
        fi

        echo "Oracle SQL*Plus setup completed successfully."

    - name: Setup Oracle Tools (Windows)
      if: ${{ runner.os == 'Windows' }}
      id: setup-oracle-tools-windows
      shell: pwsh
      run: |
        $oracleDir = "C:\oracle_client"
        if (!(Test-Path $oracleDir)) { New-Item -ItemType Directory -Path $oracleDir }

        $urlBasic = "https://download.oracle.com/otn_software/nt/instantclient/2326000/instantclient-basic-windows.x64-23.26.0.0.0.zip"
        $urlSqlPlus = "https://download.oracle.com/otn_software/nt/instantclient/2326000/instantclient-sqlplus-windows.x64-23.26.0.0.0.zip"

        Write-Host "Downloading Oracle packages..."
        Invoke-WebRequest -Uri $urlBasic -OutFile "$oracleDir\basic.zip"
        Invoke-WebRequest -Uri $urlSqlPlus -OutFile "$oracleDir\sqlplus.zip"

        Write-Host "Extracting packages..."
        Expand-Archive -Path "$oracleDir\basic.zip" -DestinationPath $oracleDir -Force
        Expand-Archive -Path "$oracleDir\sqlplus.zip" -DestinationPath $oracleDir -Force

        $extractedFolder = Get-ChildItem -Path $oracleDir -Directory | Select-Object -ExpandProperty FullName -First 1
        
        echo "$extractedFolder" >> $env:GITHUB_PATH
        echo "ORACLE_HOME=$extractedFolder" >> $env:GITHUB_ENV
        echo "TNS_ADMIN=$extractedFolder" >> $env:GITHUB_ENV

        Write-Host "Successfully configured Oracle Client at: $extractedFolder"
        refreshenv
        Write-Host "Verifying SQL*Plus installation..." -Foreground Yellow
        sqlplus -V

        if ($LASTEXITCODE -ne 0) {
            Write-Host "SQL*Plus verification failed."
            exit 1
        } else {
            Write-Host "SQL*Plus is installed and verified successfully."
        }

    - name: Verify SQL*Plus installation
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        Write-Host "Verifying SQL*Plus installation..." -Foreground Yellow
        sqlplus -V

        if ($LASTEXITCODE -ne 0) {
            Write-Host "SQL*Plus verification failed."
            exit 1
        } else {
            Write-Host "SQL*Plus is installed and verified successfully."
        }
