FROM python:3.12-alpine

WORKDIR /usr/local/ansible

COPY . .

RUN apk add unzip && \
    \
    pip install ansible pywinrm boto3 botocore
    
CMD ["ansible-playbook", "playbook.yaml", "-i", "inventory.ini"]
